# -*- coding: utf-8 -*-
"""MLA_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B3hDxtRsE34szVOcmVUg0Bk9USj8vr0r

**MACHINE LEARNING ALGORITHM | PRACTICAL - 02**

**AIM:** Implement Naïve Bayes Classifier on data set of your choice. Test and Compare for
Accuracy and Precision.
"""

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score

# Step 1: Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Step 2: Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Create a Naïve Bayes classifier and fit the training data
model = GaussianNB()
model.fit(X_train, y_train)

# Step 4: Make predictions on the test set
y_pred = model.predict(X_test)

# Step 5: Calculate accuracy and precision
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')

# Step 6: Print the accuracy and precision
print("Accuracy:", accuracy)
print("Precision:", precision)