# -*- coding: utf-8 -*-
"""MLA07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YzfAs57FoEkp5yDp94TS7ZV0r_ZTxvHq

***MACHINE LEARNING ALGORITHM | PRACTICAL 07 ***

***AIM:*** Implement K-Means Clustering and Hierarchical clustering on proper data set of your
choice. Compare their Convergence.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import silhouette_score

# Step 1: Load the Iris dataset
iris = load_iris()
X = iris.data

# Step 2: Perform K-Means clustering
kmeans = KMeans(n_clusters=3, random_state=42)
kmeans_labels = kmeans.fit_predict(X)
kmeans_score = silhouette_score(X, kmeans_labels)

# Step 3: Perform Hierarchical clustering
hierarchical = AgglomerativeClustering(n_clusters=3)
hierarchical_labels = hierarchical.fit_predict(X)
hierarchical_score = silhouette_score(X, hierarchical_labels)

# Step 4: Compare the convergence scores
print("K-Means Silhouette Score:", kmeans_score)
print("Hierarchical Silhouette Score:", hierarchical_score)